[package]
name = "rowan-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = "0.29.0"
rowan = "0.14.1"
tokenizer = { path = "../tokenizer" }
